cache:
  directories:
    - $HOME/.composer/cache

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - TESTBENCH_VERSION=^4.0
  - TESTBENCH_VERSION=^5.0

install:
  - composer global require --no-interaction --prefer-dist --update-no-dev hirak/prestissimo
  - composer require --no-interaction --prefer-dist orchestra/testbench:$TESTBENCH_VERSION

jobs:
  include:
    - stage: code-analysis
      script: make style-check
      php: 7.3
      env: TESTBENCH_VERSION=^5.0
    - stage: code-analysis
      script: static-analysis
      php: 7.3
      env: TESTBENCH_VERSION=^5.0
    - stage: test
      script: make test
